### ISSUE TITLE
Chromosome identifier ignored when regions file is supplied with -c

### ISSUE THREAD

**Issue by toedling** [aradenbaugh/radia#6]
When I call radia.py with the -c argument, supplying a bed file, the second argument, the chromosome identifier (e.g. "22"), seems to be ignored. 
The supplied bed file does contain regions on all chromosomes. And the VCF file output by radia.py also contains all chromosomes, not only the one selected chromosome.

However, when "-c" is not used, only the picked chromosome is containted in the VCF file.

I observed this with radio version 1.1.3

**Comment by aradenbaugh** [comment]
Sorry for the confusion.  Originally, the radia.py script was written to run on each chromosome separately (using the second argument) in the command.  Later, the ability to query certain ranges was added via the -c argument.  At that point, the second argument chromosome should have become an optional parameter, but in order to have backward compatibility, it was left in and ignored.  It will most likely become an optional parameter in a future version which will make it clearer.  As you correctly stated, the radia.py script runs in the following way:

1) If you specify a coordinates file via the -c parameter, it will process all (chromosome, start, stop) tuples that are provided and ignore the chromosome specified in the second argument.

2) If you don’t specify a coordinates file via the -c parameter, it will process the entire chromosome provided in the second argument.  (Or you may also specify one range by providing one start (-a) and stop (-z) parameter when using the chromosome in the second argument.)

Note:  There is a new parameter called --loadCoordinatesRange that improves performance when you are doing many small lookups in a relatively small range (e.g. looking up many 1 base sites in a 10k region).

Let me know if you have any other questions or issues.
